M48
; DRILL file {KiCad 9.0.7} date 2026-02-19T18:50:31+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-19T18:50:31+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.100
%
G90
G05
T1
X142.124Y-84.257
X142.124Y-90.037
T2
X118.415Y-94.209
X118.44Y-64.567
X150.368Y-64.237
X150.52Y-94.056
M30
